# Intent Categories
INTENT_ANALYZE_SMS = "ANALYZE_SMS"
INTENT_ANALYZE_SCREENSHOT = "ANALYZE_SCREENSHOT"
INTENT_ANALYZE_VOICE = "ANALYZE_VOICE"
INTENT_ANALYZE_DOCUMENT = "ANALYZE_DOCUMENT"
INTENT_GUARDIAN = "GUARDIAN"
INTENT_HISTORY = "HISTORY"
INTENT_HELP = "HELP"
INTENT_SETTINGS = "SETTINGS"
INTENT_ABOUT = "ABOUT"
INTENT_UNKNOWN = "UNKNOWN"

# Onboarding and Conversation State Flow States
STATE_WELCOME = "WELCOME"
STATE_AWAITING_NAME = "AWAITING_NAME"
STATE_AWAITING_GUARDIAN_NUMBER = "AWAITING_GUARDIAN_NUMBER"
STATE_AWAITING_LANGUAGE = "AWAITING_LANGUAGE"
STATE_ACTIVE = "ACTIVE"

# Support Languages
LANGUAGES = {
    "en": "English",
    "hi": "Hindi",
    "te": "Telugu",
    "ta": "Tamil",
    "kn": "Kannada"
}

DEFAULT_LANGUAGE = "hi-IN" # Hindi
